# -*- coding: utf-8 -*-
"""CNN+FPN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G7CJzl1IrszJ3lfBabWnbGVdyw8fEWRr

## **CNN+FPN**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import os
from sklearn.metrics import roc_curve, auc, classification_report
import seaborn as sn; sn.set(font_scale=1.4)
from sklearn.utils import shuffle
import cv2
import tensorflow as tf
from sklearn import metrics
from tqdm import tqdm
import pickle
import pandas as pd
import PIL
from tensorflow.keras import layers
from pathlib import Path
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, Callback
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.models import Model
from keras import Input
from keras.models import Sequential, Model, load_model
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from keras import regularizers
from keras.utils import plot_model
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.metrics import confusion_matrix, classification_report, cohen_kappa_score
import h5py
from tqdm import tqdm
import matplotlib.pyplot as plt
import math
from random import randint
from IPython.display import Image
from keras.layers import Input,ZeroPadding2D, Dropout, concatenate, Reshape, Activation, BatchNormalization, AveragePooling2D, GlobalAveragePooling2D
import matplotlib.cm as cma
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/Autism-Dataset-CNN.zip"

class_names = ['Autistic','Non_Autistic']
class_names_label = {class_name:i for i, class_name in enumerate(class_names)}
nb_classes = len(class_names)

IMAGE_SIZE = (200, 200)

def load_data():

    datasets = ['/content/Autism-Dataset-CNN/train', '/content/Autism-Dataset-CNN/test']
    output = []

    # Iterate through training and test sets
    for dataset in datasets:

        images = []
        labels = []

        print("Loading {}".format(dataset))

        # Iterate through each folder corresponding to a category
        for folder in os.listdir(dataset):
            label = class_names_label[folder]

            # Iterate through each image in our folder
            for file in tqdm(os.listdir(os.path.join(dataset, folder))):

                # Get the path name of the image
                img_path = os.path.join(os.path.join(dataset, folder), file)

                # Open and resize the img
                image = cv2.imread(img_path)
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                image = cv2.resize(image, IMAGE_SIZE)

                # Append the image and its corresponding label to the output
                images.append(image)
                labels.append(label)

        images = np.array(images, dtype = 'float32')
        labels = np.array(labels, dtype = 'int32')

        output.append((images, labels))

    return output

(train_images, train_labels), (test_images, test_labels) = load_data()

train_images, train_labels = shuffle(train_images, train_labels, random_state=25)

n_train = train_labels.shape[0]
n_test = test_labels.shape[0]

print ("Number of training examples: {}".format(n_train))
print ("Number of testing examples: {}".format(n_test))
print ("Each image is of size: {}".format(IMAGE_SIZE))

train_images = train_images / 255.0
test_images = test_images / 255.0

def display_examples(class_names, images, labels):
    fig = plt.figure(figsize=(10,10))
    fig.suptitle("Some examples of images of the dataset", fontsize=16)
    for i in range(25):
        plt.subplot(5,5,i+1)
        plt.xticks([])
        plt.yticks([])
        plt.grid(False)
        plt.imshow(images[i], cmap=plt.cm.binary)
        plt.xlabel(class_names[labels[i]])
    plt.show()

display_examples(class_names, train_images, train_labels)

# Define the input
input_layer = tf.keras.layers.Input(shape=(200, 200, 3))

# Backbone layers
backbone = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', padding='same', name='conv1'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', name='conv2'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same', name='conv3'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv4'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv5'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv6'),
    tf.keras.layers.MaxPooling2D(2, 2)
])(input_layer)

# Feature pyramid network layers
C3, C4, C5, C6 = backbone, backbone, backbone, backbone

# Top-down pathway

P6 = tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='P6')(C6)
P5 = tf.keras.layers.Add(name='add_P5')([
    tf.keras.layers.UpSampling2D(size=(1, 1), name='upsample_P6')(P6),
    tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='C5_reduced')(C5)
])
P4 = tf.keras.layers.Add(name='add_P4')([
    tf.keras.layers.UpSampling2D(size=(1, 1), name='upsample_P5')(P5),
    tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='C4_reduced')(C4)
])
P3 = tf.keras.layers.Add(name='add_P3')([
    tf.keras.layers.UpSampling2D(size=(1, 1), name='upsample_P4')(P4),
    tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='C3_reduced')(C3)
])

# gap_layer = GlobalAveragePooling2D()(backbone)
x = tf.keras.layers.Flatten()(P3)
# 512 neuron hidden layer
x = tf.keras.layers.Dense(512, activation='relu')(x)
# Only 1 output neuron. It will contain a value from 0-1 where 0 for 1 class ('dandelions') and 1 for the other ('grass')
output_layer = tf.keras.layers.Dense(1, activation='sigmoid')(x)
# # Add a single output node with sigmoid activation
# output_layer = Dense(1, activation='sigmoid')(gap_layer)

model = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

model.compile(loss='binary_crossentropy',
optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
metrics='accuracy')

model.summary()

history = model.fit(train_images, train_labels,steps_per_epoch=8,epochs=100,verbose=1,validation_data=(test_images, test_labels),validation_steps=8)

import pandas as pd

df=pd.DataFrame(history.history)
df

df['accuracy'].max(),df['accuracy'].min()

df['val_accuracy'].max(),df['val_accuracy'].min()

df['loss'].max(),df['loss'].min()

preds = model.predict(test_images,verbose=1)

from sklearn.metrics import accuracy_score, confusion_matrix

# preds = model.predict(test_data)

acc = accuracy_score(test_labels, np.round(preds))*100
cm = confusion_matrix(test_labels, np.round(preds))
tn, fp, fn, tp = cm.ravel()

print('CONFUSION MATRIX ---------')
print(cm)

print('\nTEST METRICS -----------')
precision = tp/(tp+fp)*100
recall = tp/(tp+fn)*100
print('Accuracy: {}%'.format(acc))
print('Precision: {}%'.format(precision))
print('Recall: {}%'.format(recall))
print('F1-score: {}'.format(2*precision*recall/(precision+recall)))

print('\nTRAIN METRIC -----------')
print('Train acc: {}'.format(np.round((history.history['accuracy'][-1])*100, 2)))

score = model.evaluate(test_images, test_labels,verbose = 0)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

print(test_images.shape)

predicted = np.round(preds).reshape(280)
report = classification_report(test_labels, predicted,target_names=class_names)
print(report)

from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(test_labels, predicted)
print(cf_matrix)

import seaborn as sns
sns.heatmap(cf_matrix, annot=True)

"""# <b>Exploratory Data Analysis and Plots"""

import pandas as pd

_, train_counts = np.unique(train_labels, return_counts=True)
_, test_counts = np.unique(test_labels, return_counts=True)
pd.DataFrame({'train': train_counts,
                    'test': test_counts},
             index=class_names
            ).plot.bar()
plt.show()

plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('loss')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

fpr, tpr, _ = roc_curve(test_labels, preds)
roc_auc = auc(fpr, tpr)
plt.figure()
lw = 2
plt.plot(fpr, tpr, color='darkorange',
lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC')
plt.legend(loc="lower right")
plt.show()

