# -*- coding: utf-8 -*-
"""VGG16+FPN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vrqu6Dq0Dn2-YnDL-1KwpxciT36rSpUd

# **VGG16+FPN**
"""

import os
import numpy as np
import cv2
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras import models, layers, optimizers
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, Concatenate, Add
from tensorflow.keras.models import Model
from tensorflow.keras.utils import plot_model
from sklearn.metrics import roc_curve, auc, classification_report
import seaborn as sn; sn.set(font_scale=1.4)
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn import metrics
from tqdm import tqdm
import pickle
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/Capstone/Autism-Dataset-CNN.zip"

class_names = ['Autistic','Non_Autistic']
class_names_label = {class_name:i for i, class_name in enumerate(class_names)}
nb_classes = len(class_names)

IMAGE_SIZE = (224, 224)

def load_data():
    datasets = ['/content/Autism-Dataset-CNN/train', '/content/Autism-Dataset-CNN/test']
    output = []
    # Iterate through training and test sets
    for dataset in datasets:
        images = []
        labels = []
        print("Loading {}".format(dataset))
        # Iterate through each folder corresponding to a category
        for folder in os.listdir(dataset):
            label = class_names_label[folder]
            # Iterate through each image in our folder
            for file in tqdm(os.listdir(os.path.join(dataset, folder))):
                # Get the path name of the image
                img_path = os.path.join(os.path.join(dataset, folder), file)
                # Open and resize the img
                image = cv2.imread(img_path)
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                image = cv2.resize(image, IMAGE_SIZE)
                # Append the image and its corresponding label to the output
                images.append(image)
                labels.append(label)
        images = np.array(images, dtype = 'float32')
        labels = np.array(labels, dtype = 'int32')
        output.append((images, labels))
    return output

(train_images, train_labels), (test_images, test_labels) = load_data()

train_images, train_labels = shuffle(train_images, train_labels, random_state=25)

# test_images = np.squeeze(test_images)
# test_labels = np.squeeze(test_labels)

n_train = train_labels.shape[0]
n_test = test_labels.shape[0]

print ("Number of training examples: {}".format(n_train))
print ("Number of testing examples: {}".format(n_test))
print ("Each image is of size: {}".format(IMAGE_SIZE))

# create an instance of VGG16 with pre-trained weights
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMAGE_SIZE[0], IMAGE_SIZE[1], 3))

# model = Model(inputs=resnet.input, outputs=prediction)
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
x = base_model.output
# x = GlobalAveragePooling2D()(x)
C3,C4,C5=base_model.output,base_model.output,base_model.output

# Top-down pathway

P5 = tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='P6')(C5)
P4 = tf.keras.layers.Add(name='add_P4')([
    tf.keras.layers.UpSampling2D(size=(1, 1), name='upsample_P5')(P5),
    tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='C4_reduced')(C4)
])
P4= tf.keras.layers.UpSampling2D(size=(1, 1), name='upsample_P4')(P4)
P3 = tf.keras.layers.Add(name='add_P3')([P4,
    tf.keras.layers.Conv2D(512, (1, 1), strides=(1, 1), padding='valid', name='C3_reduced')(C3)
])


x = Flatten()(P3)
x = Dense(units=1024, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(units=512, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(units=256, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(units=128, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(units=64, activation='relu')(x)
x = Dropout(0.2)(x)
predictions = Dense(1, activation='sigmoid')(x)
model = Model(inputs=base_model.input, outputs=predictions)

x = Flatten()(base_model.output)

# # add custom layers on top of the VGG16 base model
# from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
# from tensorflow.keras.models import Model
# x = base_model.output
# x = GlobalAveragePooling2D()(x)
# x = Dense(1024, activation='relu')(x)
# predictions = Dense(1, activation='sigmoid')(x)
# model = Model(inputs=base_model.input, outputs=predictions)

# # x = base_model.output
# # x = Flatten()(x)
# # x = Dense(1, activation='sigmoid')(x)
# # # model.add(Dense(1, activation='sigmoid'))
# # predictions = Dense(nb_classes, activation='softmax')(x)

# define the model to be trained
# model = Model(inputs=base_model.input, outputs=predictions)

# freeze the layers of the pre-trained model
for layer in base_model.layers:
    layer.trainable = False

from keras.optimizers import Adam
# compile the model
model.compile(optimizer=Adam(lr=0.0001), loss='binary_crossentropy', metrics=['accuracy'])

# model.compile(loss='binary_crossentropy',
# optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
# metrics='accuracy')

# history = model.fit(train_images, train_labels, epochs=100, batch_size=32)
history = model.fit(train_images, train_labels,steps_per_epoch=8,epochs=100,verbose=1,validation_data=(test_images, test_labels),validation_steps=8)

import pandas as pd

df=pd.DataFrame(history.history)
df

df['accuracy'].max(),df['accuracy'].min()

# df['val_accuracy'].max(),df['val_accuracy'].min()

df['loss'].max(),df['loss'].min()

preds = model.predict(test_images,verbose=1)

from sklearn.metrics import accuracy_score, confusion_matrix

# preds = model.predict(test_data)

acc = accuracy_score(test_labels, np.round(preds))*100
cm = confusion_matrix(test_labels, np.round(preds))
tn, fp, fn, tp = cm.ravel()

print('CONFUSION MATRIX ---------')
print(cm)

print('\nTEST METRICS -----------')
precision = tp/(tp+fp)*100
recall = tp/(tp+fn)*100
print('Test Accuracy: {}%'.format(acc))
print('Precision: {}%'.format(precision))
print('Recall: {}%'.format(recall))
print('F1-score: {}'.format(2*precision*recall/(precision+recall)))

print('\nTRAIN METRIC -----------')
print('Train acc: {}'.format(np.round((history.history['accuracy'][-1])*100, 2)))

print(test_images.shape)

predicted = np.round(preds).reshape(280)
report = classification_report(test_labels, predicted,target_names=class_names)
print(report)

import seaborn as sns
sns.heatmap(cm, annot=True)

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label = 'val_loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

fpr, tpr, _ = roc_curve(test_labels, preds)
roc_auc = auc(fpr, tpr)
plt.figure()
lw = 2
plt.plot(fpr, tpr, color='darkorange',
lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC')
plt.legend(loc="lower right")
plt.show()

